ALTER TABLE entries ALTER COLUMN longitude DROP NOT NULL;
ALTER TABLE entries ALTER COLUMN latitude DROP NOT NULL;
ALTER TABLE entries ALTER COLUMN description DROP NOT NULL;
ALTER TABLE entries ALTER COLUMN image_url DROP NOT NULL;
