ALTER TABLE entries ALTER COLUMN longitude SET NOT NULL;
ALTER TABLE entries ALTER COLUMN latitude SET NOT NULL;
ALTER TABLE entries ALTER COLUMN description SET NOT NULL;
ALTER TABLE entries ALTER COLUMN image_url SET NOT NULL;
